import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomRootLayout from "@/components/layout/CustomeRootLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomRootLayout>{children}</CustomRootLayout>
      </body>
    </html>
  );
}
